# Site settings
title: Jefferson
description: Jefferson
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Jefferson Engineer
user_description: - Nada hiere a Chao, yo soy invisible.
-Se dice invencible y no lo eres, solo eres un enfermo de M..., ¡YA Baja de ahi o te vas a morir!,
- Que dices?, Como ascesinas a quien ya esta muerto, JA-JA-JA-JA-JA.
user_title: Enginner 
email: jeffersonquiguantar@gmail.com
twitter_username: 
github_username:  jefersonqui
gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
